version: '3.8'

services:
  back:
    build:
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    container_name: grignotte_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/grignotte-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

  frontend:
    build:
      context: ../front
    container_name: grignotte_frontend
    image: node:lts
    ports:
      - 8080:8080
    volumes:
      - ../front/src:/app/src

  db:
    image: postgres
    restart: always
    user: postgres
    container_name: grignotte_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: grignotte-db
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:


